"""Initial schema with 10 recipient limit

Revision ID: f3f37db5d6a6
Revises: 801930372dd6
Create Date: 2025-12-26 01:58:37.479326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f37db5d6a6'
down_revision = '801930372dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

